name: flutter_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  # Step5: 画像をアプリケーションから呼び出すためにこちらに追記が必要です。
  # ref. https://docs.flutter.dev/ui/layout/tutorial#step-5-implement-the-image-section
  assets:
    - images/lake.jpg